### ISSUE TITLE
v1.5.2 retrieves list as str

### ISSUE THREAD

**Issue by Girgitt** [Attumm/redis-dict#10]
Maybe I am doing something wrong but storing simple list is not possible with version 1.5.2
Retrieved value is casted to str. 
```
>>> d[1] = list([1 for i in range(10)])
>>> d
{'1': '[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]'}
>>> d[1]
'[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]'
```

**Comment by Girgitt** [comment]
value saved to redis seems to have a proper type preserved: 
![image](https://user-images.githubusercontent.com/10582029/144514090-cf240518-f116-40e2-9d0c-ed4204044267.png)

**Comment by Girgitt** [comment]
Description from readme explains this behavior: 

> redis-dict can be used as a drop-in replacement for a normal dictionary as long as no datastructures are used by reference. i.e. no nested layout e.g. values such **list**,.

So it's not a bug, it's a feature type of thing..

**Comment by Attumm** [comment]
Hi @Girgitt,

First of thank you for bring this up.

If you would like to store a list then we should add it as a feature.

For a while there have been some discussions about storing referenced types too.

Do you have more usecases that would like to do with Redis-dict?

**Comment by Attumm** [comment]
New version 1.6.0 with experimental support for list, and dicts. 

```
>>> dic = RedisDict(namespace='bar')
>>> dic['a'] = ['a', 'b', 'c']
>>> dic['a']
['a', 'b', 'c']
```

Let me know if this solves your use-case.

**Comment by Girgitt** [comment]
@Attumm thanks for a quick response. I already changed my use case to avoid storing lists but will take another shot soon and let you know how it worked.

**Comment by Attumm** [comment]
@Girgitt Any luck with testing?

I rather not close the issue myself.

**Comment by Attumm** [comment]
A version has been released that does offer a initial support for lists and dicts.

**Comment by Girgitt** [comment]
@Attumm thank you for the change. I used the ability to overload serialization method and used your lib to handle lists just fine. So for my use case, the functionality is sufficient - in fact, redis-dict makes the scale-up of FastAPI straightforward and easy.
