### ISSUE TITLE
conda-forge packaging

### ISSUE THREAD

**Issue by mrakitin** [Attumm/redis-dict#31]
Dear developer(s),

My name is Max Rakitin, and I am a computational scientist at NSLS-II. Thanks for the nice package to deal with redis communication nicely!

We would like to use the package in our production, however, we use conda for our deployments, and the package was not available on any [anaconda.org channels](https://anaconda.org/search?q=redis-dict). I was going to create a conda-forge feedstock/package for this project (using the `grayskull pypi redis-dict` command), however, it indicated that the `sdist` (source distribution) was not available on PyPI at https://pypi.org/project/redis-dict/#files. It is possible to create a feedstock based on the GitHub releases/tags, however, I don't see the latest version 2.2.0 tag [here](https://github.com/Attumm/redis-dict/tags) - the latest version listed is 2.1.0.

My questions are:
1) Are you willing to co-maintain the conda-forge feedstock?
2) Could you please upload the source distribution to PyPI for the latest version?
3) Could you please add a tag/release to GitHub for the latest version 2.2.0 which is on PyPI already? This step is not so critical as long as the previous item is addressed.

Thanks! Looking forward to your feedback.

Regards,
Max Rakitin

**Comment by mrakitin** [comment]
FYI, I've started the work via https://github.com/conda-forge/staged-recipes/pull/25025 using version 2.1.0 for now.

Please leave a note if you'd like to be added as a maintainer to the feedstock. Maintainers can be added later once the feedstock is created as well, so it's not a blocker.

**Comment by Attumm** [comment]
Dear Max Rakitin,

Thank you for your interest in our package and for the great suggestion. I would be glad to co-maintain the conda-forge feedstock.
I've updated the PyPI version to v.2.3.1 to address the discrepancies you've flagged. 

For future releases, how should we keep consistency between PyPI and the conda-forge feedstock? 

Best Regards,

**Comment by mrakitin** [comment]
Hi @Attumm, thanks for your willingness to be involved. On the conda-forge side, there is a bot that tracks new versions of the software and submits a PR to the corresponding feedstock. The maintainers' role is to review the changes, fix any issues or missing dependencies, and approve/merge. There is an auto-merge capability, and it works pretty well for some feedstocks.

The feedstock is live now: https://github.com/conda-forge/redis-dict-feedstock. I'll add you to the list of maintainers.

**Comment by mrakitin** [comment]
Unfortunately, in the [latest release on PyPI](https://pypi.org/project/redis-dict/2.3.1/#files) there is only the wheel file, but no tar.gz source distribution, therefore this version can be rebuilt with conda from PyPI. If you could, please upload the sdist tarball as well. Thank you!

**Comment by mrakitin** [comment]
Please follow the instructions at https://github.com/conda-forge/redis-dict-feedstock/commit/349014acc76e3cbe0f2c3dbde1c34b2546899213#commitcomment-137478662 to accept the invitation.

**Comment by Attumm** [comment]
https://github.com/Attumm/redis-dict/issues/31#issuecomment-1901742044
```python
setup(
    name='redis dict',
```
Ah, that is correct. I found the issue.
Because the project name is "redis dict," the tar.gz filename became "redis dict-2.3.1.tar.gz," leading to the file not being uploaded, because the file contained a space.
 
Python build did add a underscore for the "redis_dict-2.3.1-py3-none-any.whl" file thus creating a partial failure.

I solved it by adding the underscore manually. Eventually we will need to update the name in setup.py, but that could have some unforeseen consequences. I guess you don't have time machine, so we can change name in the setup file?

Looking at older uploads of [redis-dict](https://pypi.org/project/redis-dict/1.4/#files) the space was allowed back then.

**Comment by Attumm** [comment]
> Please follow the instructions at [conda-forge/redis-dict-feedstock@349014a#commitcomment-137478662](https://github.com/conda-forge/redis-dict-feedstock/commit/349014acc76e3cbe0f2c3dbde1c34b2546899213#commitcomment-137478662) to accept the invitation.

@mrakitin Accepted the invitation, Thanks again for your great work; it's appreciated.

**Comment by mrakitin** [comment]
Hi @Attumm! I think this issue is mostly resolved as we have the working feedstock repo https://github.com/conda-forge/redis-dict-feedstock and the package is on conda-forge now: https://anaconda.org/conda-forge/redis-dict (the same latest version as on PyPI at the moment - [v2.3.2](https://pypi.org/project/redis-dict/2.3.2/)).

**Comment by Attumm** [comment]
@mrakitin  Great work, thanks a ton for helping with Conda.
And making the project available for those that prefer or need Conda.
