### ISSUE TITLE
import fails for version v2.4 in python 3.9 

### ISSUE THREAD

**Issue by Girgitt** [Attumm/redis-dict#44]
In version v.2.4 (tested tags v.2.4.0 and v.2.4.1) RedisDict cannot be imported under python 3.9 due to syntax error: 

```python
    from redis_dict import RedisDict
  File "/home/zbig/repos/bess/modbus_rest_proxy/venv_linux_py39/lib/python3.9/site-packages/redis_dict.py", line 79, in <module>
    class RedisDict:
  File "/home/zbig/repos/bess/modbus_rest_proxy/venv_linux_py39/lib/python3.9/site-packages/redis_dict.py", line 643, in RedisDict
    def expire_at(self, sec_epoch: int | timedelta) -> Iterator[None]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

```
redis_dict.py: 642-3
```python
    @contextmanager
    def expire_at(self, sec_epoch: int | timedelta) -> Iterator[None]:
```
Writing union types as **int | timedelta** is not supported in python 3.9

Tag v.2.3 works fine.

**Comment by Attumm** [comment]
Thanks for bringing the issue to my attention.
In the future, it will be time to create a testing pipeline for different Python versions.
With GitHub CI.

Please check out the latest version, v2.5.0; the issue should be resolved :)

**Comment by Attumm** [comment]
@Girgitt Did you get a chance to check if the issue still persists with the latest version?
