### ISSUE TITLE
populate from big dict

### ISSUE THREAD

**Issue by rmrmg** [Attumm/redis-dict#8]
I want to move big dict (~100M entries) to redis-dict. Assignment single element in loop
```
for elem in pydict:
    redisdict[elem]=pydict[elem]
```
is rather slow is there any better way for this?

**Comment by Attumm** [comment]
Yes there is.
The issue there is that it's doing round trips to redis.
To solve it you can use pipeline to make one round trip.

```python
with redis_dic.pipeline():
    for k, v in pydict.items():
        redis_dic[k] = v
````
